sudo: required
services:
    - docker

before_install:
    - docker build -t lloydcapson/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true lloydcapson/react-test npm test

after_success:
    - docker build -t lloydcapson/multi-client ./client
    - docker build -t lloydcapson/multi-nginx ./nginx
    - docker build -t lloydcapson/multi-server ./server
    - docker build -t lloydcapson/multi-worker ./worker

    